In [1]:
import numpy as np

a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [2]:
import time

a = np.random.rand(1000000)
b = np.random.rand(1000000)

tic = time.time()
c = np.dot(a,b)
toc = time.time()

print(c)
print("Vectorized :" + str(1000*(toc-tic))+"ms" )

c = 0

tic = time.time()
for i in range(1000000):
    c+=a[i]*b[i]
    
toc = time.time()
print(c)
print("For loop :" + str(1000*(toc-tic))+"ms" )

250039.25386628474
Vectorized :1572.8785991668701ms
250039.25386628154
For loop :506.6995620727539ms


# Broadcasting example


In [3]:
A = np.array([[56.0,0.0,4.4,68.0],
             [1.2,104.0,52.0,8.0],
             [1.8,135.0,99.0,0.9]]
            )
print(A)

[[ 56.    0.    4.4  68. ]
 [  1.2 104.   52.    8. ]
 [  1.8 135.   99.    0.9]]


In [4]:
cal = A.sum(axis = 0)
print(cal)

[ 59.  239.  155.4  76.9]


In [5]:
percentage = 100* A/cal.reshape(1,4)
print(percentage)

[[94.91525424  0.          2.83140283 88.42652796]
 [ 2.03389831 43.51464435 33.46203346 10.40312094]
 [ 3.05084746 56.48535565 63.70656371  1.17035111]]


# Tricks and tips

In [6]:
a = np.random.randn(5)
print(a)

[-1.43872777 -0.57045613  0.4007051  -0.47051453  2.25682919]


In [7]:
print(a.shape) # rank 1 array (don't use in code)

(5,)


In [8]:
print(a.T)

[-1.43872777 -0.57045613  0.4007051  -0.47051453  2.25682919]


In [9]:
print(np.dot(a,a.T))

7.8705843036951055


In [10]:
a = np.random.randn(5,1)
print(a)

[[ 1.76823969]
 [ 2.23749882]
 [-0.82621531]
 [-0.21624679]
 [-1.69511523]]


In [11]:
print(a.T)

[[ 1.76823969  2.23749882 -0.82621531 -0.21624679 -1.69511523]]


In [12]:
print(np.dot(a,a.T))

[[ 3.12667161  3.95643422 -1.46094671 -0.38237615 -2.99737003]
 [ 3.95643422  5.00640096 -1.84865578 -0.48385193 -3.79281832]
 [-1.46094671 -1.84865578  0.68263174  0.17866641  1.40053016]
 [-0.38237615 -0.48385193  0.17866641  0.04676267  0.36656322]
 [-2.99737003 -3.79281832  1.40053016  0.36656322  2.87341563]]


In [13]:
assert(a.shape==(5,1))

In [14]:
a = np.random.randn(4,3)
b = np.random.randn(3,2)
c = a*b
c

ValueError: operands could not be broadcast together with shapes (4,3) (3,2) 